### ISSUE TITLE
void:classPartition classes not usable as class parameter value

### ISSUE THREAD

**Issue by simeonvandersteen** [bbcarchdev/spindle#30]
spindle_home produces a list of internal URIs but these don't work as class parameter values. 

Instead of for example http://[api-domain]/works, http://purl.org/vocab/frbr/core#Work does work.

So, either the produced list is incorrect, or the query (spindle_query_db) is incorrect.

**Comment by nevali** [comment]
It _expands_ internal _request_ URIs to full class _query_ URIs. There is no reason why anybody would ever perform a `?class=...` query using one of the local class partition request URIs.

If you visit `/works`, this is the _equivalent_ of passing `/?class=http://purl.org/vocab/frbr/core%23Work`

This is so that class partitions and class queries can share an implementation (because they do the same thing).

The missing bit, which should be added at some point, is redirecting a `/?class=...` query to the defined class partition if one exists... and also making the class partitions configurable in `quilt.conf`.
