### ISSUE TITLE
Collection not correctly updated on partial updates

### ISSUE THREAD

**Issue by simeonvandersteen** [bbcarchdev/spindle#77]
Because of [this](https://github.com/bbcarchdev/spindle/blob/develop/twine/generate/describe.c#L41), [this](https://github.com/bbcarchdev/spindle/blob/develop/twine/generate/describe.c#L114) isn't executed on partial (`TK_MEMBERSHIP`) updates, so that [this guy](https://github.com/bbcarchdev/spindle/blob/develop/twine/generate/index-membership.c#L59) is missing the graphs URIs.

Then stuff doesn't end up in the collection.

**Comment by nevali** [comment]
Ahh, I see. Is `data->sourcedata` populated when not performing a full update? (i.e., is it just the iteration that's skipped?) if so that should be a straightforward, if slightly annoying, fix… the population of the strset should probably be moved to wherever the population of `data->sourcedata` happens for clarity's sake though.

**Comment by simeonvandersteen** [comment]
Yeah it's just the iteration that's skipped on partial updates, so [this](https://github.com/bbcarchdev/spindle/blob/develop/twine/generate/describe.c#L114) should probably happen in `source.c`

**Comment by nevali** [comment]
Yup, exactly that 👍
