### ISSUE TITLE
The message queue is not informed of the usage of a cluster

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/spindle#83]
https://github.com/bbcarchdev/spindle/blob/develop/twine/generate/mq.c#L295 always evaluates to False

**Comment by cgueret** [comment]
Fixed by adding a call to libmq and using that call from twine:
https://github.com/bbcarchdev/libmq/commit/401a5ec0d420ee3f5d2e5d54311374a95fcd25ea
https://github.com/bbcarchdev/libmq/commit/f970578157e25e513cf42527c2539746849645d1
https://github.com/bbcarchdev/twine/commit/c56f7f7b7126777a0f3b4e0cd4cd373d5f1c49a3
https://github.com/bbcarchdev/twine/commit/0b3762d17a7ee7b5b0f16f81e07338adad0441db
https://github.com/bbcarchdev/twine/commit/0a6524743f9361edc52513fe2180de134fcd45ba

**Comment by nevali** [comment]
Technically this isn't a spindle bug at all, however!

In future it'd be really helpful for tracking to ensure that issues are broken down as they're tracked through the different projects (cross-project references are easy in GH Issues), and referencing the issue number in the relevant commits. So in this case there'd be two issues — one in Twine, and one (for the missing API call implementation) in libmq, with this closed as invalid and pointing at the Twine bug instead.

(Otherwise it gets tricky to figure out what's changing/where/why)

**Comment by cgueret** [comment]
You're right. We first identified this bug as being related to spindle (and tried to solve it as such) but while working on the fix figured out the solution had to be implemented in libmq and twine. Hence the dodgy situation for this issue...
